import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientAuthProvider from "../components/ClientAuthProvider";
import { validateEnvironmentOnStartup } from "../utils/env-validation";
import { NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';
import translations from '../../locales/en.json';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Validate environment variables on startup
  validateEnvironmentOnStartup();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={translations}>
          <ClientAuthProvider>{children}</ClientAuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
