import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientAuthProvider from "../components/ClientAuthProvider";
import { validateEnvironmentOnStartup } from "../utils/env-validation";
// Temporarily disable next-intl to test basic deployment
// import { NextIntlClientProvider } from 'next-intl';
// import { getMessages } from 'next-intl/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Validate environment variables on startup
  validateEnvironmentOnStartup();

  // Temporarily disable next-intl
  // const messages = await getMessages();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Temporarily disable NextIntlClientProvider */}
        {/* <NextIntlClientProvider messages={messages}> */}
          <ClientAuthProvider>{children}</ClientAuthProvider>
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}
